import fs from 'fs';
import path from 'path';

// Load emojis
const emojisPath = path.join(process.cwd(), 'data', 'emojis.json');
const emojis = JSON.parse(fs.readFileSync(emojisPath, 'utf8'));

const xeonbrutal = (prefix) => {
        return `🔥 *BRUTAL CONTENT* 🔥

╔══════════════════════════════════╗
║     🎭 XEON BRUTAL DISPLAY 🎭      ║  
║                                  ║
║  ⚡ Premium Text Art Content ⚡    ║
║  🌟 Exclusive Design Elements 🌟   ║
║  💀 Dark Mode Aesthetics 💀       ║
║                                  ║
║  ┌─────────────────────────────┐  ║
║  │  BRUTAL TEXT ART CONTENT    │  ║
║  │  ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓  │  ║
║  │  ████████████████████████  │  ║
║  │  ░░░░░░░░░░░░░░░░░░░░░░░░  │  ║
║  │  ▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  │  ║
║  └─────────────────────────────┘  ║
║                                  ║
║  🎯 Special Characters: ꪶ𖣂ꫂ        ║
║  🔮 Unicode Art Elements          ║
║  ⭐ Premium Design Package        ║
║                                  ║
║  💎 BRUTAL MODE ACTIVATED 💎      ║
╚══════════════════════════════════╝

🤖 *Generated by HORLA POOKIE Bot*
⚡ *Command:* ${prefix}brutal
🎮 *Category:* Games & Fun`
}

export default {
  name: "brutal",
  description: "Display brutal text art and content",
  aliases: ["xbrutal", "brutalmsg"],
  async execute(msg, { sock, args, settings }) {
    const from = msg.key.remoteJid;
    const prefix = settings?.prefix || '.';

    try {
      const brutalContent = xeonbrutal(prefix);
      
      await sock.sendMessage(from, {
        text: brutalContent
      }, { quoted: msg });

      // Success reaction
      await sock.sendMessage(from, {
        react: { text: emojis.success || '✅', key: msg.key }
      });

    } catch (error) {
      console.error('Brutal command error:', error);
      await sock.sendMessage(from, {
        text: `${emojis.error || '❌'} *Error displaying brutal content*\n\n🔧 *Error:* ${error.message}`
      }, { quoted: msg });

      await sock.sendMessage(from, {
        react: { text: emojis.error || '❌', key: msg.key }
      });
    }
  }
};