import fs from 'fs';
import path from 'path';

const emojisPath = path.join(process.cwd(), 'data', 'emojis.json');
const emojis = JSON.parse(fs.readFileSync(emojisPath, 'utf8'));

export default {
  name: 'grok',
  description: 'Generate AI image using Grok-style AI (Flux model)',
  aliases: ['grok-img'],
  async execute(msg, { sock, args }) {
    const from = msg.key.remoteJid;

    if (!args || args.length === 0) {
      return await sock.sendMessage(from, {
        text: `${emojis.ai || '🤖'} *GROK AI Image Generator*\n\n🎨 Generate stunning images with Flux AI!\n\n*Usage:* ?grok <your prompt>\n*Example:* ?grok a futuristic city at sunset\n\n✨ Free — no login required!`
      }, { quoted: msg });
    }

    const prompt = args.join(' ');
    if (prompt.length > 500) {
      return await sock.sendMessage(from, {
        text: `${emojis.warning || '⚠️'} Prompt is too long. Please keep it under 500 characters.`
      }, { quoted: msg });
    }

    try {
      await sock.sendMessage(from, {
        react: { text: '🎨', key: msg.key }
      });
      await sock.sendMessage(from, {
        text: `🎨 *Generating Grok AI image...*\n\n📝 *Prompt:* ${prompt}\n\n⏳ Please wait...`
      }, { quoted: msg });

      const encodedPrompt = encodeURIComponent(prompt);
      const seed = Math.floor(Math.random() * 99999);
      const imageUrl = `https://image.pollinations.ai/prompt/${encodedPrompt}?width=1024&height=1024&model=flux&seed=${seed}&nologo=true&enhance=true`;

      await sock.sendMessage(from, {
        image: { url: imageUrl },
        caption: `${emojis.success || '✅'} *Image Generated!*\n\n🎨 *Prompt:* ${prompt}\n\n✨ *Generated by GROK AI*\n\n> Powered by Eclipse MD`
      }, { quoted: msg });

      await sock.sendMessage(from, {
        react: { text: '✅', key: msg.key }
      });

    } catch (error) {
      console.error('Grok command error:', error.message);
      await sock.sendMessage(from, {
        text: `${emojis.error || '❌'} Failed to generate image. Please try again.\n\n🔧 ${error.message}`
      }, { quoted: msg });
      await sock.sendMessage(from, {
        react: { text: '❌', key: msg.key }
      });
    }
  }
};
